apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: expense-tool-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/beabhuv/trpc-go-expense-pilot.git
    path: charts/backend
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
